# Generated by Django 6.0.3 on 2026-10-09 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0033_remove_team_organisation_delete_organisation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='earned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='resilia.affiliate')),
                ('referred_subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affiliate_commissions', to='resilia.subscription')),
            ],
        ),
    ]
