# Generated by Django 6.0.3 on 2026-10-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resilia', '0034_affiliatecommission'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='affiliatecommission',
            constraint=models.UniqueConstraint(fields=('referred_subscription',), name='unique_affiliate_commission_per_subscription'),
        ),
    ]
